export const books = [
	{
		id: 1,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
	{
		id: 2,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
	{
		id: 3,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
	{
		id: 4,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
	{
		id: 5,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
	{
		id: 6,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: true,
		price: 15,
	},
	{
		id: 7,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
	{
		id: 8,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
	{
		id: 9,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
	{
		id: 10,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
	{
		id: 11,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
	{
		id: 12,
		title: 'The house at the edge of magic',
		image: '/assets/img/Img Product.png',
		author: 'A. Sparkes',
		rating: 4,
		isSoldOut: false,
		price: 15,
	},
]
